export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const AUTH_SET_LOADING = "AUTH_SET_LOADING";
export const AUTH_NOTIFICATION = "AUTH_NOTIFICATION";

export const PRESENTATION_ADD = 'PRESENTATION_ADD';
export const PRESENTATION_FETCH = 'PRESENTATION_FETCH';
export const PRESENTATION_COLLABORATE_FETCH = 'PRESENTATION_COLLABORATE_FETCH';
export const PRESENTATIONS_FETCH = 'PRESENTATIONS_FETCH';
export const PRESENTATION_LOADING = 'PRESENTATION_LOADING';

export const USER_FETCH = 'USER_FETCH';